import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header / Navigation
    'nav.why': 'Why a Website',
    'nav.process': 'Our Process',
    'nav.pricing': 'Pricing',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    'nav.book': 'Book a Call',

    // Home Page
    'hero.headline1': "Your business deserves",
    'hero.headline2': "a real online presence.",
    'hero.badge': 'Online in 7-14 days · From $500',
    'hero.cta': "Let's talk, it's free",
    'hero.scroll': 'Scroll',
    'hero.proof.satisfaction': '100% Satisfied Clients',
    'hero.proof.quality': '5-Star Quality',
    'hero.proof.guarantee': 'Personal Follow-up',
    'globalForm.title': 'Tell me about your situation',
    'globalForm.subtitle': "One message is enough. I get back to you within 24 hours, always.",
    'home.viewPricing': 'See Prices',
    'home.valueProps.title1': 'What a real website',
    'home.valueProps.title2': 'does for your business',
    'home.valueProps.subtitle': 'Many businesses could reach more clients online with a stronger web presence. Here\'s what a well-built site actually changes.',
    'home.value1.title': 'Found by the right people',
    'home.value1.desc': 'Every day, people search for exactly what you offer. A well-positioned site makes sure it\'s your name they find.',
    'home.value2.title': 'Credibility from the first visit',
    'home.value2.desc': 'A professional site builds trust before anyone reaches out. Visitors arrive already confident in who you are.',
    'home.value3.title': 'Your site works while you rest',
    'home.value3.desc': 'While you work, sleep, or take a weekend, your site is answering questions, presenting your services, and bringing in new inquiries.',
    'home.cta.title': 'Ready to grow your online presence?',
    'home.cta.subtitle': 'Free 30-min call. We look at your situation together and I tell you honestly what I can do for you.',
    'home.cta.button': 'Book my free call',
    
    // Home Contact Methods
    'home.contact.title1': "Let's talk,",
    'home.contact.title2': 'no commitment',
    'home.contact.subtitle': 'No sales pitch, no pressure. Just an honest conversation about what you actually need.',
    'home.contact.recommended': 'Recommended',
    'home.contact.call.title': 'Book a Free 30-min Call',
    'home.contact.call.desc': 'We look at your situation together. I\'ll tell you honestly what can bring you more clients and exactly how.',
    'home.contact.call.cta': 'Choose a time slot',
    'home.contact.whatsapp.desc': 'A quick question? A project idea? Drop me a message. I usually reply within minutes.',
    'home.contact.whatsapp.cta': 'Send a message',
    'home.contact.email.desc': "Prefer email? Tell me about your situation and I'll come back with concrete ideas within 24 hours.",

    // Stats / Value Props
    'stats.always.title': 'Clients even while you sleep',
    'stats.always.desc': 'Your site never takes a day off. While you rest, it collects inquiries, builds trust, and finds new clients for you.',
    'stats.trust.title': 'They trust you before calling',
    'stats.trust.desc': 'People Google before they call. A professional site is what turns a curious visitor into someone who reaches out.',
    'stats.mobile.title': '7 in 10 visitors are on mobile',
    'stats.mobile.desc': 'If your site isn\'t optimized for mobile, most visitors leave before reading a word. Every site I build looks great on every screen.',
    'stats.cta': 'Discover the process',
    'stats.cta.link': '/our-process',

    // Why a Website Page
    'why.title1': 'Without a website,',
    'why.title2': "you\'re hard to find.",
    'why.subtitle': 'Before contacting anyone, people look them up online. What they find, or don\'t find, shapes the decision.',
    'why.pain1.title': 'Invisible on Google',
    'why.pain1.desc': 'Even people actively searching for your service find your competitors first. If you\'re not showing up, you simply don\'t exist online.',
    'why.pain2.title': 'No credibility before the first call',
    'why.pain2.desc': 'Without a website, clients can\'t check you out. They move on to someone they can verify online. You never even know they were interested.',
    'why.pain3.title': 'Leads slipping away around the clock',
    'why.pain3.desc': 'No contact form means no messages at night, no inquiries on weekends. Every hour without a site is an opportunity window left wide open for someone else.',
    'why.pain4.title': 'Stuck relying on referrals',
    'why.pain4.desc': 'Word-of-mouth is unpredictable and impossible to scale. Without a site, you have no system to attract new clients on your own terms.',
    'why.solution.label': 'The fix',
    'why.solution.title1': 'With a professional site,',
    'why.solution.title2': 'everything changes.',
    'why.benefit1.title': 'Found on Google',
    'why.benefit1.desc': 'When someone searches for your service in your area, your name comes up first, not your competitor\'s.',
    'why.benefit2.title': 'Inquiries around the clock',
    'why.benefit2.desc': 'Your contact form works nights, weekends, and holidays. You wake up to messages already waiting.',
    'why.benefit3.title': 'A fast return on investment',
    'why.benefit3.desc': 'One or two new clients from your site and it\'s already paid for itself. After that, it keeps delivering.',
    'why.benefit4.title': 'Trust before the first word',
    'why.benefit4.desc': 'A professional site signals credibility instantly. Visitors arrive already convinced of who you are before reaching out.',
    'why.comparison.title': 'The difference is clear',
    'why.comparison.without': 'Without a Website',
    'why.comparison.with': 'With a Professional Site',
    'why.without.item1': 'Hard to find on Google, even for people looking for you',
    'why.without.item2': 'No online presence means less trust before the first call',
    'why.without.item3': 'Entirely dependent on referrals and word-of-mouth',
    'why.without.item4': 'No way to be reached outside of working hours',
    'why.with.item1': 'Visible on Google in your city and sector',
    'why.with.item2': 'Instant credibility: visitors trust you before reaching out',
    'why.with.item3': 'New inquiries coming in even when you\'re not working',
    'why.with.item4': 'Reachable 24/7, without any extra effort on your part',
    'why.cta.title': 'Ready to be more visible online?',
    'why.cta.subtitle': 'Browse the plans and pick what fits your situation.',
    'why.cta.button': 'See Prices',

    // Our Process Page
    'process.title1': 'From first conversation',
    'process.title2': 'to live website, in 4 steps',
    'process.subtitle': 'No jargon, no surprises. Here\'s exactly how we work together.',
    'process.step1.title': 'Free 30-min Call',
    'process.step1.desc': 'We talk about your business, your clients, your goals. I ask the right questions so I understand what will actually work for you, not just what looks good.',
    'process.step2.title': 'I Design Your Site',
    'process.step2.desc': 'I build a design tailored to your brand that gives visitors a reason to get in touch. You validate, I adjust until it\'s exactly right.',
    'process.step3.title': 'I Build & Optimize Everything',
    'process.step3.desc': 'I develop the site, set up your Google visibility (SEO), and make sure everything loads fast on every device.',
    'process.step4.title': 'Launch',
    'process.step4.desc': 'Your site goes live. I walk you through everything, and stay available if you have questions down the line.',
    'process.cta.title': "It's more straightforward than you'd think.",
    'process.cta.subtitle': 'One free 30-min call. We look at your situation together and you leave with a clear idea of what to do.',
    'process.cta.button': 'Book My Free Call',

    // Pricing Page
    'pricing.title1': 'Simple pricing,',
    'pricing.title2': 'real results.',
    'pricing.subtitle': 'No hidden fees, no surprises. Here\'s exactly what each plan includes.',
    'pricing.maintenance.toggle': 'Add Monthly Maintenance',
    'pricing.maintenance.desc': 'I handle everything: updates, security, hosting. Your site always runs perfectly, without you thinking about it.',
    'pricing.maintenance.custom': 'Custom',
    'pricing.guarantee.title': 'Not satisfied? I keep working.',
    'pricing.guarantee.desc': 'If the result doesn\'t feel right, I rework it until you\'re fully happy with what you have. No extra cost.',

    // Services (shared with pricing)
    'services.title': 'The plan that fits your needs',
    'services.title1': 'The plan that',
    'services.title2': 'fits your needs',
    'services.subtitle': 'Whether you\'re just getting started or building everything at once, there\'s an option that fits where you are.',
    'services.landing.title': 'Single-Page Site',
    'services.landing.price': '$500',
    'services.landing.desc': 'Everything you need on one sharp page, so visitors find you, trust you, and reach out to you.',
    'services.landing.feature1': 'Looks great on every device (phone, tablet, desktop)',
    'services.landing.feature2': 'Visible on Google in your area (basic SEO included)',
    'services.landing.feature3': 'Live in 7 to 14 business days',
    'services.landing.cta': 'Get started',
    
    'services.authority.title': 'Showcase Website',
    'services.authority.price': '$1500',
    'services.authority.desc': 'Your full online presence. Clients find you on Google, see you\'re the real deal, and choose you over the competitor down the street.',
    'services.authority.feature1': 'Multiple pages: home, services, about, contact',
    'services.authority.feature2': 'Serious Google SEO: you rank ahead of local competitors',
    'services.authority.feature3': 'Visitors can reach you directly from the site',
    'services.authority.feature4': 'Fast and flawless on mobile (7 in 10 visitors are on their phone)',
    'services.authority.cta': 'Get my site',
    'services.authority.popular': 'Most Popular',
    
    'services.custom.title': 'Full Launch Pack',
    'services.custom.price': '$3500',
    'services.custom.desc': 'Your complete digital identity from day one. Website, professional videos, social media content & launch, SEO, and Google Ads if you want.',
    'services.custom.feature1': 'Showcase site + visual identity (logo, colors, fonts)',
    'services.custom.feature2': 'Professional videos & filmmaking for your brand',
    'services.custom.feature3': 'Ready-to-post content for your social media (photos, videos, captions)',
    'services.custom.feature4': 'Full setup & launch of your social media accounts',
    'services.custom.feature5': 'Advanced Google SEO to rank ahead in your sector',
    'services.custom.feature6': 'Google Ads launch (optional): Google, Facebook & Instagram',
    'services.custom.cta': "Let's talk",
    'pricing.quote.title': 'Something more specific?',
    'pricing.quote.title1': 'Something',
    'pricing.quote.title2': 'more specific?',
    'pricing.quote.desc': 'Your project doesn\'t fit neatly into a plan? No problem. Tell me what you need and I\'ll put together a quote around it.',
    'pricing.quote.cta': 'Get a custom quote',
    'pricing.quote.q1': 'Already have a site and want to rebuild it?',
    'pricing.quote.q2': 'E-commerce, booking system, member area?',
    'pricing.quote.q3': 'Need something completely custom?',
    'pricing.quote.q4': 'Not sure yet what you need?',

    // Portfolio
    'portfolio.title1': 'Real projects,',
    'portfolio.title2': 'measurable results',
    'portfolio.subtitle': 'See what it looks like when a website actually works.',
    'portfolio.preview': 'Live Preview',
    'portfolio.luxura.name': 'Luxura Spa',
    'portfolio.luxura.category': 'Wellness & Beauty',
    'portfolio.luxura.desc': 'Elegant, high-converting design that communicates luxury before a single word is read.',
    'portfolio.steel.name': 'Steel & Pipe Plumbing',
    'portfolio.steel.category': 'Home Services',
    'portfolio.steel.desc': 'Built to generate trust and calls. Brings in 50+ leads every month.',
    'portfolio.cta.title': 'Your business could look like this too.',
    'portfolio.cta.subtitle': 'Let\'s talk about what we can realistically build for you.',
    'portfolio.cta.button': 'Book a Free Strategy Call',

    // Testimonials
    'testimonials.title1': 'They were in your position.',
    'testimonials.title2': 'Now they have results.',
    'testimonials.subtitle': 'Real feedback from business owners who went through the process.',
    'testimonials.cta': 'See the Work',
    'testimonials.cta.link': '/portfolio',
    'testimonial.1.text': "We needed a site that matched our energy. Elie understood our world straight away. The result is sharp, professional, and exactly what we were after.",
    'testimonial.1.author': 'VM Producers',
    'testimonial.1.founder': 'Austin Talley',
    'testimonial.1.role': 'Event Production Agency',
    'testimonial.1.date': 'Jan 2026',
    'testimonial.2.text': "Elie perfectly captured our brand's essence. The site reflects our ambition and our values. We got great feedback right from launch, and traffic has really taken off.",
    'testimonial.2.author': 'Solar Fusion',
    'testimonial.2.founder': 'Sébastien Chaffardon',
    'testimonial.2.role': 'Founder, Solar Fusion',
    'testimonial.2.date': 'Nov 2025',
    'testimonial.3.text': "Working with Elie was a real revelation. Our site now inspires trust, converts better, and our clients tell us so. Careful, attentive work from start to finish.",
    'testimonial.3.author': 'MyWebGlory',
    'testimonial.3.founder': 'Gabriel Ageron',
    'testimonial.3.role': 'Founder, MyWebGlory',
    'testimonial.3.date': 'Dec 2025',

    // Popup
    'popup.title': "Most people search online before reaching out to a business.",
    'popup.subtitle': "Are they finding you? Let's find out.",
    'popup.cta': 'Book my free call',
    'popup.close': 'Not right now',

    // Contact Page
    'contact.title1': "Let's talk",
    'contact.title2': "about your situation",
    'contact.subtitle': 'Free, no commitment. I listen to what you need and tell you honestly what I can do, and what I can\'t.',
    'contact.calendly.title': 'Book a Free 30-min Call',
    'contact.calendly.desc': 'We look at your situation together. You leave with a clear idea of what to do, whether you work with me or not.',
    'contact.calendly.button': 'Choose a slot',
    'contact.form.title': 'Send Me a Message',
    'contact.name': 'Your name',
    'contact.email': 'Your email',
    'contact.project': 'Tell me about your situation',
    'contact.send': 'Send message',
    'contact.sending': 'Sending...',
    'contact.success': 'Message sent! I\'ll get back to you within 24 hours.',

    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.made': 'Made with passion',

    // Apps Page
    'apps.hero.badge': 'Custom Internal Apps',
    'apps.hero.h1a': 'Your team deserves',
    'apps.hero.h1b': 'better than a spreadsheet.',
    'apps.hero.desc': 'Dashboards, CRM, management tools, automation. I build custom internal web apps that replace Excel spreadsheets and manual processes.',
    'apps.hero.cta1': "Let's discuss your project",
    'apps.hero.cta2': 'See pricing',
    'apps.hero.stat1': 'weeks delivery',
    'apps.hero.stat2': 'custom-built',
    'apps.hero.stat3': 'available online',
    'apps.types.badge': 'Services',
    'apps.types.title': 'Apps that work the way you do',
    'apps.types.subtitle': 'Custom internal web apps to digitize your processes, centralize your data, and save time every day.',
    'apps.type1.title': 'Dashboards & Reporting',
    'apps.type1.desc': 'Visualize your data in real time. KPIs, charts, custom dashboards to steer your business.',
    'apps.type1.ex1': 'Analytics dashboard',
    'apps.type1.ex2': 'HR dashboard',
    'apps.type1.ex3': 'Financial reporting',
    'apps.type1.ex4': 'Performance tracking',
    'apps.type2.title': 'CRM & Client Management',
    'apps.type2.desc': 'Manage your contacts, opportunities, and client follow-up in an interface tailored to your business.',
    'apps.type2.ex1': 'Sales pipeline',
    'apps.type2.ex2': 'Quote/invoice tracking',
    'apps.type2.ex3': 'Client history',
    'apps.type2.ex4': 'Automated reminders',
    'apps.type3.title': 'E-commerce Back-office',
    'apps.type3.desc': 'Custom admin interface to manage your orders, stock, and clients without relying on Shopify or WooCommerce.',
    'apps.type3.ex1': 'Order management',
    'apps.type3.ex2': 'Stock tracking',
    'apps.type3.ex3': 'Sales stats',
    'apps.type3.ex4': 'Returns management',
    'apps.type4.title': 'Operations Management',
    'apps.type4.desc': 'Centralize your operations in one tool: task tracking, scheduling, cross-team coordination.',
    'apps.type4.ex1': 'Site / job tracking',
    'apps.type4.ex2': 'Team scheduling',
    'apps.type4.ex3': 'Ticket management',
    'apps.type4.ex4': 'Cross-department workflows',
    'apps.type5.title': 'Automation & AI',
    'apps.type5.desc': 'Connect your tools and automate your processes. AI integration to save time on repetitive tasks.',
    'apps.type5.ex1': 'Scraping & enrichment',
    'apps.type5.ex2': 'Automated report generation',
    'apps.type5.ex3': 'Internal chatbot',
    'apps.type5.ex4': 'Automated workflows',
    'apps.type6.title': 'Field & Mobile Apps',
    'apps.type6.desc': 'Mobile web apps for your field teams: accessible anywhere, no installation, straight from the browser.',
    'apps.type6.ex1': 'Technician / delivery app',
    'apps.type6.ex2': 'Digital delivery notes',
    'apps.type6.ex3': 'Field reports',
    'apps.type6.ex4': 'Quality checklists',
    'apps.why.badge': 'Why custom-built',
    'apps.why.title': 'Your process. Your tool.',
    'apps.why.subtitle': 'Off-the-shelf SaaS tools are built for everyone, meaning they\'re perfect for no one.',
    'apps.why1.title': 'Built for YOUR processes',
    'apps.why1.desc': 'No compromise. The app adapts to how you work, not the other way around. Done with workarounds in generic tools.',
    'apps.why2.title': 'Your data, yours to keep',
    'apps.why2.desc': 'You own your database. No SaaS subscription, no risk of shutdown, no dependency.',
    'apps.why3.title': 'Measurable ROI',
    'apps.why3.desc': 'A tool that eliminates 2 hours of manual data entry per day pays for itself within weeks. Your teams get more efficient from day one.',
    'apps.process.badge': 'Process',
    'apps.process.title': 'How does it work?',
    'apps.process.subtitle': 'A clear, transparent process with no surprises.',
    'apps.step1.title': 'Discovery',
    'apps.step1.desc': 'We analyze your current process, your tools, and define exactly what the app needs to solve.',
    'apps.step2.title': 'Specs & Wireframes',
    'apps.step2.desc': 'I deliver a detailed functional plan and mockups to validate the experience before a single line of code is written.',
    'apps.step3.title': 'Development',
    'apps.step3.desc': 'Iterative development with regular demos. You see the app take shape week after week.',
    'apps.step4.title': 'Delivery & Support',
    'apps.step4.desc': 'Deployment, team onboarding, and post-launch support to make sure everything runs smoothly.',
    'apps.pricing.badge': 'Pricing',
    'apps.pricing.title': 'Transparent pricing',
    'apps.pricing.subtitle': 'Every project is unique. These ranges give you a reference point. We refine together on a free first call.',
    'apps.pricing.note': 'All prices are excluding tax · 50% deposit upfront, balance on delivery',
    'apps.pricing.popular': 'Most popular',
    'apps.pricing.cta': "Let's discuss your project",
    'apps.plan1.title': 'Starter App',
    'apps.plan1.price': '$2,500',
    'apps.plan1.desc': 'A targeted internal tool to digitize one key process. Say goodbye to spreadsheets, sticky notes, and missed follow-ups.',
    'apps.plan1.f1': 'Up to 3 functional modules',
    'apps.plan1.f2': 'Responsive admin interface',
    'apps.plan1.f3': 'User authentication',
    'apps.plan1.f4': 'Database included',
    'apps.plan1.f5': 'Online deployment',
    'apps.plan1.f6': '1 month of support included',
    'apps.plan2.title': 'Business App',
    'apps.plan2.price': '$5,000',
    'apps.plan2.desc': 'Complete internal tool with role management, analytics dashboard, and connections to your existing software.',
    'apps.plan2.f1': 'Unlimited modules',
    'apps.plan2.f2': 'Multi-roles (admin, user, manager...)',
    'apps.plan2.f3': 'Built-in analytics dashboard',
    'apps.plan2.f4': 'Third-party API integrations (ERP, CRM...)',
    'apps.plan2.f5': 'Email / SMS notifications',
    'apps.plan2.f6': 'Excel / PDF export',
    'apps.plan2.f7': '3 months of support included',
    'apps.plan3.title': 'Custom',
    'apps.plan3.price': 'Custom quote',
    'apps.plan3.desc': 'Advanced internal tool ecosystem: multiple departments, complex business logic, embedded AI.',
    'apps.plan3.f1': '100% custom architecture',
    'apps.plan3.f2': 'Advanced AI / automation',
    'apps.plan3.f3': 'Multi-site or multi-entity',
    'apps.plan3.f4': 'Team onboarding & training',
    'apps.plan3.f5': 'Long-term maintenance',
    'apps.plan3.f6': 'Ongoing product coaching',
    'apps.faq.badge': 'FAQ',
    'apps.faq.title': 'Frequently asked questions',
    'apps.faq.q1': 'How long does it take to build an internal app?',
    'apps.faq.a1': 'A simple tool (Starter) generally takes 3 to 5 weeks. A full multi-module tool (Business) takes 6 to 10 weeks. For larger projects, we define the timeline together on the first call.',
    'apps.faq.q2': 'What technologies do you use?',
    'apps.faq.a2': 'React + TypeScript for the front-end, Node.js / Supabase for the back-end, deployed on Vercel or a VPS depending on the needs. Modern, maintainable, and scalable choices.',
    'apps.faq.q3': 'Will my teams need training?',
    'apps.faq.a3': 'I design interfaces to be intuitive from the start. A handover session is included in all plans. I also provide user guides if needed.',
    'apps.faq.q4': 'Do you handle hosting too?',
    'apps.faq.a4': 'Yes. I handle the full deployment and can manage hosting (included for 1 year in Starter and Business plans). After that, it\'s roughly €10-30/month depending on your needs.',
    'apps.faq.q5': 'Can the app connect to our existing tools (ERP, accounting, Slack...)?',
    'apps.faq.a5': 'Absolutely. Third-party API integrations are included in the Business App plan. Sage, HubSpot, Slack, Airtable, Zapier, Google Sheets: if it has an API, we can connect it.',
    'apps.cta.title': 'Your idea deserves a real app',
    'apps.cta.desc': 'A 30-minute call is all it takes to see if I can help. It\'s free, no commitment, and you leave with concrete ideas.',
    'apps.cta.button': 'Book a free call',

    // Portfolio Page - Extra
    'portfolio.badge': 'This could be your site',
    'portfolio.showcase.mywebglory.category': 'Event Marketing Agency',
    'portfolio.showcase.mywebglory.cta': 'Discover MyWebGlory',
    'portfolio.showcase.mywebglory.desc': 'Built to convert visitors into clients. Modern design, intuitive flow, and every element designed to get people to reach out.',
    'portfolio.showcase.solarfusion.category': 'Solar Energy Company',
    'portfolio.showcase.solarfusion.cta': 'Discover Solar Fusion',
    'portfolio.showcase.solarfusion.desc': 'A site that positions Solar Fusion as the obvious choice in their market, and keeps generating leads week after week.',
    'portfolio.showcase.vmproducers.category': 'Event Production Agency',
    'portfolio.showcase.vmproducers.cta': 'Discover VM Producers',
    'portfolio.showcase.vmproducers.desc': 'A high-impact site built for a music production label. Bold, memorable, and designed to attract artists and collaborators.',
  },
  fr: {
    // Header / Navigation
    'nav.why': 'Pourquoi un Site',
    'nav.process': 'Notre Méthode',
    'nav.pricing': 'Tarifs',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    'nav.book': 'Réserver un appel',

    // Home Page
    'hero.headline1': "Votre business mérite",
    'hero.headline2': "une vraie présence en ligne.",
    'hero.badge': 'En ligne en 7-14 jours · Dès 500€',
    'hero.cta': 'Discutons-en, c\'est gratuit',
    'hero.scroll': 'Défiler',
    'hero.proof.satisfaction': '100% Clients satisfaits',
    'hero.proof.quality': 'Qualité 5 étoiles',
    'hero.proof.guarantee': 'Suivi personnalisé',
    'globalForm.title': 'Parlez-moi de votre projet',
    'globalForm.subtitle': 'Un message suffit. Je vous réponds sous 24h.',
    'home.viewPricing': 'Voir les tarifs',
    'home.valueProps.title1': 'L\'impact',
    'home.valueProps.title2': 'd\'un vrai site web',
    'home.valueProps.subtitle': 'Beaucoup d\'entreprises pourraient toucher plus de clients en ligne, simplement avec une meilleure présence. Voici trois différences concrètes.',
    'home.value1.title': 'Plus de clients',
    'home.value1.desc': 'Les gens qui cherchent votre service sur Google vous trouvent en premier.',
    'home.value2.title': 'Confiance immédiate',
    'home.value2.desc': 'Un site professionnel = les gens vous prennent au sérieux avant même de vous contacter.',
    'home.value3.title': 'Vous travaillez, il vend',
    'home.value3.desc': 'Votre site travaille jour et nuit. Il répond aux questions, convainc, et collecte des contacts, même pendant que vous dormez.',
    'home.cta.title': 'Prêt à avoir plus de clients en ligne ?',
    'home.cta.subtitle': 'Réservez un appel gratuit de 30 min. J\'analyse votre situation et je vous dis ce qu\'un site peut concrètement faire pour vous.',
    'home.cta.button': 'Réserver mon appel gratuit',
    
    // Home Contact Methods
    'home.contact.title1': 'Discutons',
    'home.contact.title2': 'sans engagement',
    'home.contact.subtitle': 'Choisissez comment vous souhaitez échanger. Pas de discours de vente, juste une conversation directe.',
    'home.contact.recommended': 'Recommandé',
    'home.contact.call.title': 'Appel gratuit 30 min',
    'home.contact.call.desc': 'Nous analysons ensemble votre situation, je vous indique clairement ce qui peut vous apporter des clients et comment.',
    'home.contact.call.cta': 'Choisir un créneau',
    'home.contact.whatsapp.desc': 'Une question ? Une idée de projet ? Envoyez-moi un message, je réponds en général dans la minute.',
    'home.contact.whatsapp.cta': 'Envoyer un message',
    'home.contact.email.desc': "Vous préférez écrire ? Décrivez-moi votre situation, je reviens avec des idées concrètes sous 24h.",

    // Stats / Value Props
    'stats.always.title': 'Des clients, même la nuit',
    'stats.always.desc': 'Votre site ne prend pas de congé. Pendant que vous vous reposez, il collecte des demandes, répond aux questions, et vous trouve de nouveaux clients.',
    'stats.trust.title': 'Ils vous font confiance avant d\'appeler',
    'stats.trust.desc': 'Les gens se renseignent en ligne avant de contacter. Un site professionnel est ce qui transforme un visiteur curieux en quelqu\'un qui prend contact.',
    'stats.mobile.title': '7 visiteurs sur 10 sont sur mobile',
    'stats.mobile.desc': 'Si votre site n\'est pas optimisé pour mobile, la plupart de vos visiteurs repartent sans rien lire. Chaque site que je crée est parfait sur tous les écrans.',
    'stats.cta': 'Découvrir la méthode',
    'stats.cta.link': '/our-process',

    // Why a Website Page
    'why.title1': 'Sans site web,',
    'why.title2': 'vous passez inaperçu',
    'why.subtitle': 'Aujourd\'hui, avant de contacter un professionnel, les gens le cherchent en ligne. Ce qu\'ils trouvent, ou ne trouvent pas, fait toute la différence.',
    'why.pain1.title': 'Invisible sur Google',
    'why.pain1.desc': 'Même les personnes qui cherchent activement votre service trouvent vos concurrents à votre place. Si vous n\'apparaissez pas, vous n\'existez tout simplement pas en ligne.',
    'why.pain2.title': 'Aucune crédibilité avant le premier appel',
    'why.pain2.desc': 'Sans site, les clients ne peuvent pas vous jauger. Ils passent à quelqu\'un qu\'ils peuvent vérifier en ligne. Vous ne saurez jamais qu\'ils s\'étaient intéressés.',
    'why.pain3.title': 'Des contacts perdus en permanence',
    'why.pain3.desc': 'Pas de formulaire de contact = pas de messages la nuit, pas de demandes le week-end. Chaque heure sans site, c\'est une opportunité offerte à quelqu\'un d\'autre.',
    'why.pain4.title': 'Dépendant du bouche-à-oreille',
    'why.pain4.desc': 'Les recommandations sont imprévisibles et impossibles à scaler. Sans site, vous n\'avez aucun système pour attirer de nouveaux clients par vos propres moyens.',
    'why.solution.label': 'La solution',
    'why.solution.title1': 'Avec un site professionnel,',
    'why.solution.title2': 'tout change.',
    'why.benefit1.title': 'Trouvé sur Google',
    'why.benefit1.desc': 'Quand quelqu\'un cherche votre service dans votre zone, c\'est vous qui apparaissez en premier, pas votre concurrent.',
    'why.benefit2.title': 'Des contacts à toute heure',
    'why.benefit2.desc': 'Votre formulaire tourne la nuit, le week-end, les jours fériés. Vous vous réveillez avec des messages qui vous attendent.',
    'why.benefit3.title': 'Un investissement vite rentabilisé',
    'why.benefit3.desc': 'Un ou deux nouveaux clients via votre site et c\'est déjà remboursé. Ensuite il continue de travailler pour vous.',
    'why.benefit4.title': 'La confiance avant le premier mot',
    'why.benefit4.desc': 'Un site professionnel inspire confiance immédiatement. Les visiteurs arrivent déjà convaincus de qui vous êtes avant même de vous contacter.',
    'why.comparison.title': 'La différence est concrète',
    'why.comparison.without': 'Sans Site Web',
    'why.comparison.with': 'Avec un Site Professionnel',
    'why.without.item1': 'Difficile à trouver pour quelqu\'un qui vous cherche',
    'why.without.item2': 'Moins de crédibilité sans présence en ligne visible',
    'why.without.item3': 'Entièrement dépendant du bouche-à-oreille',
    'why.without.item4': 'Injoignable en dehors des horaires de travail',
    'why.with.item1': 'Visible sur Google dans votre ville et secteur',
    'why.with.item2': 'Crédibilité immédiate, les visiteurs vous font confiance avant de contacter',
    'why.with.item3': 'Des demandes qui arrivent même quand vous ne travaillez pas',
    'why.with.item4': 'Joignable 24h/24, sans effort supplémentaire de votre part',
    'why.cta.title': 'Prêt à améliorer votre présence en ligne ?',
    'why.cta.subtitle': 'Regardez les formules et choisissez celle qui correspond à votre projet.',
    'why.cta.button': 'Voir les Tarifs',

    // Our Process Page
    'process.title1': 'De zéro à en ligne',
    'process.title2': 'en 4 étapes simples',
    'process.subtitle': 'Pas de jargon, pas de surprise. Voici exactement comment cela se déroule lorsque vous travaillez avec moi.',
    'process.step1.title': 'Appel gratuit (30 min)',
    'process.step1.desc': 'Nous échangeons sur votre activité, vos clients, vos objectifs. Je pose les bonnes questions pour comprendre ce qui fonctionnera réellement pour vous.',
    'process.step2.title': 'Je crée votre design',
    'process.step2.desc': 'Je crée un design à votre image qui donne envie aux visiteurs de vous contacter. Vous validez, j\'ajuste jusqu\'à ce que ce soit parfait.',
    'process.step3.title': 'Je développe et optimise',
    'process.step3.desc': 'Je développe le site, je configure la visibilité Google (référencement), et je m\'assure que tout charge vite sur tous les appareils.',
    'process.step4.title': 'Lancement : vous êtes en ligne',
    'process.step4.desc': 'Votre site est mis en ligne. Je vous forme à l\'utiliser, et je suis disponible si vous avez des questions.',
    'process.cta.title': 'Prêt à vous lancer ?',
    'process.cta.subtitle': 'Réservez votre appel gratuit. 30 minutes suffisent pour déterminer si nous sommes en adéquation pour travailler ensemble.',
    'process.cta.button': 'Réserver mon appel gratuit',

    // Pricing Page
    'pricing.title1': 'Des tarifs clairs,',
    'pricing.title2': 'des résultats concrets.',
    'pricing.subtitle': 'Pas de frais cachés, pas de surprises. Voici exactement ce que chaque formule inclut.',
    'pricing.maintenance.toggle': 'Ajouter la maintenance mensuelle',
    'pricing.maintenance.desc': 'Je m\'occupe de tout : mises à jour, sécurité, hébergement. Votre site tourne toujours parfaitement, sans que vous y pensiez.',
    'pricing.maintenance.custom': 'Sur mesure',
    'pricing.guarantee.title': 'Pas satisfait ? Je retravaille.',
    'pricing.guarantee.desc': 'Si le résultat ne vous convient pas, je refais jusqu\'\u00e0 ce que vous soyez pleinement satisfait. Sans frais supplémentaires.',

    // Services (shared with pricing)
    'services.title': 'Choisissez la formule adaptée à votre projet',
    'services.title1': 'La formule',
    'services.title2': "qu'il vous faut",
    'services.subtitle': 'Que vous démarriez ou que vous construisiez tout d\'un coup, il y a une option qui correspond à où vous en êtes.',
    'services.landing.title': 'Site Une Page',
    'services.landing.price': '500€',
    'services.landing.desc': 'Une page claire et efficace pour présenter votre offre et pousser les visiteurs à vous contacter.',
    'services.landing.feature1': 'S\'affiche parfaitement sur tous les appareils (téléphone, tablette, ordinateur)',
    'services.landing.feature2': 'Visible sur Google dans votre ville (référencement de base inclus)',
    'services.landing.feature3': 'En ligne en 7 à 14 jours ouvrés',
    'services.landing.cta': 'Commencer',
    
    'services.authority.title': 'Site Vitrine',
    'services.authority.price': '1500€',
    'services.authority.desc': 'Un vrai site plusieurs pages pour que vos clients vous trouvent sur Google et vous choisissent plutôt que la concurrence.',
    'services.authority.feature1': 'Plusieurs pages : accueil, services, à propos, contact',
    'services.authority.feature2': 'Référencement Google soigné : vous apparaissez devant vos concurrents locaux',
    'services.authority.feature3': 'Les visiteurs peuvent vous contacter directement depuis le site',
    'services.authority.feature4': 'Rapide et parfait sur mobile (7 visiteurs sur 10 sont sur téléphone)',
    'services.authority.cta': 'Avoir mon site',
    'services.authority.popular': 'Le plus populaire',
    
    'services.custom.title': 'Pack Lancement Complet',
    'services.custom.price': '3500€',
    'services.custom.desc': 'Toute votre identité numérique dès le premier jour. Site web, vidéos pro, contenu réseaux sociaux, lancement de vos comptes et Google Ads si vous le souhaitez.',
    'services.custom.feature1': 'Site vitrine + identité visuelle (logo, couleurs, typographies)',
    'services.custom.feature2': 'Vidéos professionnelles & filmmaking pour votre marque',
    'services.custom.feature3': 'Contenu prêt à poster sur vos réseaux (photos, vidéos, captions)',
    'services.custom.feature4': 'Lancement & setup complet de vos réseaux sociaux',
    'services.custom.feature5': 'Référencement Google avancé (SEO) pour apparaître en tête',
    'services.custom.feature6': 'Lancement Google Ads en option (Google, Facebook & Instagram)',
    'services.custom.cta': 'Discutons-en',
    'pricing.quote.title': 'Besoins spécifiques ?',
    'pricing.quote.title1': 'Besoins',
    'pricing.quote.title2': 'spécifiques ?',
    'pricing.quote.desc': 'Votre projet ne rentre pas exactement dans une formule ? Pas de problème. Décrivez-moi ce dont vous avez besoin et je vous prépare un devis adapté.',
    'pricing.quote.cta': 'Obtenir un devis sur mesure',
    'pricing.quote.q1': 'Vous avez déjà un site et voulez le refaire ?',
    'pricing.quote.q2': 'E-commerce, prise de rendez-vous, espace membre ?',
    'pricing.quote.q3': 'Vous avez besoin de quelque chose de vraiment sur mesure ?',
    'pricing.quote.q4': 'Pas encore sûr de ce qu\'il vous faut ?',

    // Portfolio
    'portfolio.title1': 'Des projets réels,',
    'portfolio.title2': 'des résultats mesurables',
    'portfolio.subtitle': 'Découvrez ce qu\'un site performant peut accomplir pour votre activité.',
    'portfolio.preview': 'Aperçu Live',
    'portfolio.luxura.name': 'Luxura Spa',
    'portfolio.luxura.category': 'Bien-être & Beauté',
    'portfolio.luxura.desc': 'Un design élégant et ultra-convertissant qui transmet le luxe avant même qu\'on lise un mot.',
    'portfolio.steel.name': 'Steel & Pipe Plumbing',
    'portfolio.steel.category': 'Services à Domicile',
    'portfolio.steel.desc': 'Construit pour générer de la confiance et des appels. Plus de 50 contacts par mois.',
    'portfolio.cta.title': 'Votre activité peut ressembler à ça.',
    'portfolio.cta.subtitle': 'Parlons de ce qu\'on peut concrètement construire pour vous.',
    'portfolio.cta.button': 'Réserver mon appel gratuit',

    // Testimonials
    'testimonials.title1': 'Ils étaient à votre place.',
    'testimonials.title2': 'Aujourd\'hui, ils ont des résultats.',
    'testimonials.subtitle': 'Des retours honnêtes de gens qui sont passés par là.',
    'testimonials.cta': 'Voir nos réalisations',
    'testimonials.cta.link': '/portfolio',
    'testimonial.1.text': "On avait besoin d'un site à la hauteur de notre énergie. Elie a compris notre univers immédiatement. Le résultat est percutant, professionnel, exactement ce qu'on voulait.",
    'testimonial.1.author': 'VM Producers',
    'testimonial.1.founder': 'Austin Talley',
    'testimonial.1.role': 'Agence de Production Événementielle',
    'testimonial.1.date': 'Jan 2026',
    'testimonial.2.text': "Elie a su capter l'essence de notre marque. Le site reflète parfaitement notre ambition et nos valeurs. On a eu des retours très positifs dès le lancement et le trafic a vraiment décollé.",
    'testimonial.2.author': 'Solar Fusion',
    'testimonial.2.founder': 'Sébastien Chaffardon',
    'testimonial.2.role': 'Fondateur, Solar Fusion',
    'testimonial.2.date': 'Nov 2025',
    'testimonial.3.text': "Collaborer avec Elie a été une vraie révélation. Notre site inspire confiance, convertit mieux, et nos clients nous le disent. Un travail soigné, du début à la fin.",
    'testimonial.3.author': 'MyWebGlory',
    'testimonial.3.founder': 'Gabriel Ageron',
    'testimonial.3.role': 'Fondateur, MyWebGlory',
    'testimonial.3.date': 'Déc 2025',

    // Popup
    'popup.title': "La majorité des gens cherchent un professionnel en ligne avant de prendre contact.",
    'popup.subtitle': "Est-ce qu'il vous trouve ? Voyons ça ensemble.",
    'popup.cta': 'Réserver mon appel gratuit',
    'popup.close': 'Pas maintenant',

    // Contact Page
    'contact.title1': 'Parlons de',
    'contact.title2': 'votre situation',
    'contact.subtitle': 'Gratuit, sans engagement. J\'écoute ce dont vous avez besoin et je vous dis honnêtement ce que je peux faire, et ce que je ne peux pas.',
    'contact.calendly.title': 'Réserver un appel gratuit',
    'contact.calendly.desc': 'Nous analysons votre situation ensemble. Vous repartez avec une idée claire de ce qu\'il vous faut, que vous travailliez avec moi ou non.',
    'contact.calendly.button': 'Choisir un créneau',
    'contact.form.title': 'Envoyez-moi un message',
    'contact.name': 'Votre nom',
    'contact.email': 'Votre email',
    'contact.project': 'Décrivez-moi votre situation',
    'contact.send': 'Envoyer le message',
    'contact.sending': 'Envoi...',
    'contact.success': 'Message envoyé ! Je vous recontacte sous 24h.',

    // Footer
    'footer.rights': 'Tous droits réservés.',
    'footer.made': 'Fait avec passion',

    // Apps Page
    'apps.hero.badge': 'Apps internes sur mesure',
    'apps.hero.h1a': 'Votre équipe mérite',
    'apps.hero.h1b': 'mieux qu\'un tableur.',
    'apps.hero.desc': 'Dashboards, CRM, outils de gestion, automatisation. Je développe des applications web internes sur mesure qui remplacent les tableurs Excel et les processus manuels.',
    'apps.hero.cta1': 'Discutons de votre projet',
    'apps.hero.cta2': 'Voir les tarifs',
    'apps.hero.stat1': 'semaines de livraison',
    'apps.hero.stat2': 'sur mesure',
    'apps.hero.stat3': 'accessible en ligne',
    'apps.types.badge': 'Services',
    'apps.types.title': 'Des apps qui fonctionnent comme vous',
    'apps.types.subtitle': 'Des applications web internes sur mesure pour digitaliser vos processus, centraliser vos données et gagner du temps au quotidien.',
    'apps.type1.title': 'Dashboards & Reporting',
    'apps.type1.desc': 'Visualisez vos données en temps réel. KPIs, graphiques, tableaux de bord sur mesure pour piloter votre activité.',
    'apps.type1.ex1': 'Dashboard analytics',
    'apps.type1.ex2': 'Tableau de bord RH',
    'apps.type1.ex3': 'Reporting financier',
    'apps.type1.ex4': 'Suivi de performance',
    'apps.type2.title': 'CRM & Gestion Clients',
    'apps.type2.desc': 'Gérez vos contacts, opportunités et suivi client dans une interface taillée pour votre business.',
    'apps.type2.ex1': 'Pipeline commercial',
    'apps.type2.ex2': 'Suivi devis/factures',
    'apps.type2.ex3': 'Historique clients',
    'apps.type2.ex4': 'Relances automatiques',
    'apps.type3.title': 'Back-office E-commerce',
    'apps.type3.desc': 'Interface d\'administration sur mesure pour gérer vos commandes, stocks et clients sans dépendre de Shopify ou WooCommerce.',
    'apps.type3.ex1': 'Gestion commandes',
    'apps.type3.ex2': 'Suivi des stocks',
    'apps.type3.ex3': 'Stats ventes',
    'apps.type3.ex4': 'Gestion retours',
    'apps.type4.title': 'Gestion Opérationnelle',
    'apps.type4.desc': 'Centralisez vos opérations dans un outil unique : suivi des tâches, gestion des plannings, coordination inter-équipes.',
    'apps.type4.ex1': 'Suivi de chantiers',
    'apps.type4.ex2': 'Planning équipes',
    'apps.type4.ex3': 'Gestion de tickets',
    'apps.type4.ex4': 'Workflow inter-services',
    'apps.type5.title': 'Automatisation & IA',
    'apps.type5.desc': 'Connectez vos outils et automatisez vos processus. Intégration d\'IA pour gagner du temps sur les tâches répétitives.',
    'apps.type5.ex1': 'Scraping & enrichissement',
    'apps.type5.ex2': 'Génération de rapports',
    'apps.type5.ex3': 'Chatbot interne',
    'apps.type5.ex4': 'Workflows automatisés',
    'apps.type6.title': 'Apps Terrain & Mobile',
    'apps.type6.desc': 'Applications web mobile pour vos équipes sur le terrain : accessibles partout, sans installation, directement dans le navigateur.',
    'apps.type6.ex1': 'App techniciens / livreurs',
    'apps.type6.ex2': 'Bons de livraison digitaux',
    'apps.type6.ex3': 'Rapports terrain',
    'apps.type6.ex4': 'Checklist qualité',
    'apps.why.badge': 'Pourquoi sur mesure',
    'apps.why.title': 'Votre process. Votre outil.',
    'apps.why.subtitle': 'Les SaaS du marché sont faits pour tout le monde, donc pour personne en particulier.',
    'apps.why1.title': 'Adapté à VOS processus',
    'apps.why1.desc': 'Pas de compromis. L\'app s\'adapte à votre façon de travailler, pas l\'inverse. Fini les workarounds dans des outils génériques.',
    'apps.why2.title': 'Vos données, chez vous',
    'apps.why2.desc': 'Vous êtes propriétaire de votre base de données. Pas d\'abonnement SaaS, pas de risque de fermeture, pas de dépendance.',
    'apps.why3.title': 'ROI mesurable',
    'apps.why3.desc': 'Un outil qui supprime 2h de saisie manuelle par jour se rentabilise en quelques semaines. Vos équipes gagnent en efficacité dès le premier mois.',
    'apps.process.badge': 'Méthode',
    'apps.process.title': 'Comment ça se passe ?',
    'apps.process.subtitle': 'Un processus clair, transparent, sans mauvaises surprises.',
    'apps.step1.title': 'Découverte',
    'apps.step1.desc': 'On analyse votre processus actuel, vos outils, et on définit exactement ce que l\'app doit résoudre.',
    'apps.step2.title': 'Specs & Wireframes',
    'apps.step2.desc': 'Je vous livre un plan fonctionnel détaillé et des maquettes pour valider l\'expérience avant de coder.',
    'apps.step3.title': 'Développement',
    'apps.step3.desc': 'Développement itératif avec des démos régulières. Vous voyez l\'app prendre forme semaine après semaine.',
    'apps.step4.title': 'Livraison & Support',
    'apps.step4.desc': 'Déploiement, formation de votre équipe, et support post-lancement pour s\'assurer que tout roule.',
    'apps.pricing.badge': 'Tarifs',
    'apps.pricing.title': 'Des tarifs transparents',
    'apps.pricing.subtitle': 'Chaque projet est unique. Ces fourchettes vous donnent un repère. On affine ensemble lors d\'un premier appel gratuit.',
    'apps.pricing.note': 'Tous les prix sont HT · Acompte 50% au démarrage, solde à la livraison',
    'apps.pricing.popular': 'Le plus populaire',
    'apps.pricing.cta': 'Discutons de votre projet',
    'apps.plan1.title': 'Starter App',
    'apps.plan1.price': '2 500€',
    'apps.plan1.desc': 'Un outil interne ciblé pour digitaliser un processus clé : fini les tableurs, les post-its et les oublis.',
    'apps.plan1.f1': 'Jusqu\'à 3 modules fonctionnels',
    'apps.plan1.f2': 'Interface admin responsive',
    'apps.plan1.f3': 'Authentification utilisateurs',
    'apps.plan1.f4': 'Base de données incluse',
    'apps.plan1.f5': 'Déploiement en ligne',
    'apps.plan1.f6': '1 mois de support inclus',
    'apps.plan2.title': 'Business App',
    'apps.plan2.price': '5 000€',
    'apps.plan2.desc': 'Outil interne complet avec gestion des droits, analytics et connexion à vos logiciels existants.',
    'apps.plan2.f1': 'Modules illimités',
    'apps.plan2.f2': 'Multi-rôles (admin, user, manager...)',
    'apps.plan2.f3': 'Dashboard analytics intégré',
    'apps.plan2.f4': 'Intégrations API tierces (ERP, CRM...)',
    'apps.plan2.f5': 'Notifications email / SMS',
    'apps.plan2.f6': 'Export Excel / PDF',
    'apps.plan2.f7': '3 mois de support inclus',
    'apps.plan3.title': 'Sur Mesure',
    'apps.plan3.price': 'Sur devis',
    'apps.plan3.desc': 'Ecosystème d\'outils internes avancé : plusieurs départements, logique métier complexe, IA intégrée.',
    'apps.plan3.f1': 'Architecture 100% personnalisée',
    'apps.plan3.f2': 'IA / automatisation avancée',
    'apps.plan3.f3': 'Multi-sites ou multi-entités',
    'apps.plan3.f4': 'Onboarding & formation équipe',
    'apps.plan3.f5': 'Maintenance longue durée',
    'apps.plan3.f6': 'Accompagnement produit continu',
    'apps.faq.badge': 'FAQ',
    'apps.faq.title': 'Questions fréquentes',
    'apps.faq.q1': 'Combien de temps pour développer une app interne ?',
    'apps.faq.a1': 'Un outil simple (Starter) prend généralement 3 à 5 semaines. Un outil complet multi-modules (Business) de 6 à 10 semaines. Pour les projets plus larges, on définit le planning ensemble lors du premier appel.',
    'apps.faq.q2': 'Avec quelles technologies travaillez-vous ?',
    'apps.faq.a2': 'React + TypeScript pour le front-end, Node.js / Supabase pour le back-end, déploiement sur Vercel ou VPS selon les besoins. Des choix modernes, maintenables et scalables.',
    'apps.faq.q3': 'Mes équipes auront-elles besoin de formation ?',
    'apps.faq.a3': 'Je conçois les interfaces pour être intuitives dès le départ. Une session de prise en main est incluse dans toutes les offres. Je fournis aussi des guides utilisateur si nécessaire.',
    'apps.faq.q4': 'Est-ce que vous gérez aussi l\'hébergement ?',
    'apps.faq.a4': 'Oui. Je m\'occupe du déploiement complet et je peux gérer l\'hébergement (inclus 1 an dans les offres Starter et Business). Après, c\'est ~10-30€/mois selon les besoins.',
    'apps.faq.q5': 'Peut-on connecter l\'app à nos outils déjà en place (ERP, compta, Slack...) ?',
    'apps.faq.a5': 'Absolument. L\'intégration d\'APIs tierces est incluse dans l\'offre Business App. Sage, HubSpot, Slack, Airtable, Zapier, Google Sheets : si ça a une API, on peut le connecter.',
    'apps.cta.title': 'Votre idée mérite une vraie app',
    'apps.cta.desc': 'Un appel de 30 minutes suffit pour voir si je peux vous aider. C\'est gratuit, sans engagement, et vous repartez avec des idées concrètes.',
    'apps.cta.button': 'Réserver un appel gratuit',

    // Portfolio Page - Extra
    'portfolio.badge': 'Ce site pourrait être le vôtre',
    'portfolio.showcase.mywebglory.category': 'Marketing d\'Événement',
    'portfolio.showcase.mywebglory.cta': 'Découvrir MyWebGlory',
    'portfolio.showcase.mywebglory.desc': 'Conçu pour convertir les visiteurs en clients. Design moderne, navigation fluide, et chaque élément pensé pour pousser à l\'action.',
    'portfolio.showcase.solarfusion.category': 'Énergie Solaire',
    'portfolio.showcase.solarfusion.cta': 'Découvrir Solar Fusion',
    'portfolio.showcase.solarfusion.desc': 'Un site qui positionne Solar Fusion comme l\'évidence dans son secteur, et génère des contacts semaine après semaine.',
    'portfolio.showcase.vmproducers.category': 'Agence de Production Événementielle',
    'portfolio.showcase.vmproducers.cta': 'Découvrir VM Producers',
    'portfolio.showcase.vmproducers.desc': 'Un site percutant pour un label de production musicale. Audacieux, mémorable, conçu pour attirer artistes et collaborateurs.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Detect browser language
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('fr')) {
      setLanguage('fr');
    } else {
      setLanguage('en');
    }
  }, []);

  const t = (key: string): string => {
    const langTranslations = translations[language];
    return (langTranslations as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
